import { isAppLocale, type AppLocale } from "@/i18n/config";

const copies = {
    vi: {
        planning: "Đang hiểu yêu cầu và chọn năng lực sáng tạo phù hợp",
        matching: "Đang ghép kỹ năng sáng tạo với mô hình phù hợp",
        retrying: "Đang phân tích và thực thi lại yêu cầu…",
        retryingTasks: "Đang tạo lại các tác vụ thất bại…",
        completed: "Yêu cầu sáng tạo đã hoàn tất.",
        failed: "Agent thực thi thất bại",
        cancelled: "Tác vụ Agent đã bị hủy.",
        cancelRequested: "Đang hủy tác vụ và chờ xác nhận từ các tác vụ con",
        cancelPending: "Một số tác vụ con chưa xác nhận hủy; bạn có thể thử lại sau",
        paused: "Tác vụ đã tạm dừng",
        restored: "Kết nối đã được khôi phục và tác vụ đang tiếp tục",
        reconnecting: "Kết nối tạm thời gián đoạn; đang kiểm tra trạng thái tác vụ nền",
        runningInBackground: "Tác vụ vẫn đang chạy trong nền và kết nối đang được khôi phục",
        pausedInBackground: "Tiến trình đã được lưu và tác vụ hiện đang tạm dừng",
        unknownBackground: "Chưa thể xác nhận trạng thái thời gian thực; tác vụ vẫn tiếp tục trong nền",
        loginExpired: "Phiên đăng nhập đã hết hạn; tác vụ có thể vẫn chạy trong nền. Hãy đăng nhập lại để tiếp tục theo dõi",
        finishing: "Đang hoàn thiện kết quả",
    },
    en: {
        planning: "Understanding the request and selecting the right creative capabilities",
        matching: "Matching creative skills and models",
        retrying: "Reanalyzing and executing this request…",
        retryingTasks: "Regenerating failed tasks…",
        completed: "The creative request is complete.",
        failed: "Agent execution failed",
        cancelled: "The Agent task was cancelled.",
        cancelRequested: "Cancelling the task and waiting for child-task confirmation",
        cancelPending: "Some child tasks have not confirmed cancellation; you can try again later",
        paused: "The task is paused",
        restored: "The connection is restored and the task is continuing",
        reconnecting: "The connection was interrupted; checking the background task status",
        runningInBackground: "The task is still running in the background and the connection is being restored",
        pausedInBackground: "Progress is saved and the task is currently paused",
        unknownBackground: "The live status cannot be confirmed yet; the task is still continuing in the background",
        loginExpired: "Your session expired; the task may still be running in the background. Sign in again to continue watching it",
        finishing: "Preparing the final result",
    },
    "zh-CN": {
        planning: "正在理解需求并选择合适的创作能力",
        matching: "正在匹配创作技能与模型",
        retrying: "正在重新分析并执行这次请求…",
        retryingTasks: "正在重新生成失败任务…",
        completed: "创作任务已完成。",
        failed: "Agent 执行失败",
        cancelled: "Agent 任务已取消。",
        cancelRequested: "正在取消任务，等待子任务确认",
        cancelPending: "部分子任务取消状态尚未确认，可稍后再次取消",
        paused: "任务已暂停",
        restored: "连接已恢复，任务继续运行",
        reconnecting: "连接暂时中断，正在确认后台任务状态",
        runningInBackground: "任务仍在后台运行，正在恢复连接",
        pausedInBackground: "任务仍在后台保存，当前处于暂停状态",
        unknownBackground: "暂时无法确认实时状态，任务仍会在后台继续运行",
        loginExpired: "登录状态已失效，任务仍可能在后台运行；重新登录后可继续查看",
        finishing: "正在整理结果",
    },
} as const satisfies Record<AppLocale, Record<string, string>>;

export function agentRunCopy(locale?: AppLocale) {
    return copies[isAppLocale(locale) ? locale : "zh-CN"];
}
